### ISSUE TITLE
deploy it in server, make it callable

### ISSUE THREAD

**Issue by mefengl** [mefengl/play-chatgpt#2]
should be able to call use https, but a ip is also acceptable @netcyabc

**Comment by netcyabc** [comment]
Got it.

**Comment by netcyabc** [comment]
![image](https://user-images.githubusercontent.com/30020507/209155937-bbf9adf1-91e8-48da-b558-3b95f138f20f.png)
While deploying, I encounter this problem occasionally, which usually happens after my one or two questions via the API.So I started packet-tracing using Fiddler, and this is how the latter responses:
![image](https://user-images.githubusercontent.com/30020507/209156361-fa769d25-872f-4478-8e16-559a9ebb9418.png)
![image](https://user-images.githubusercontent.com/30020507/209156420-ae4c8ac2-ae9c-4299-a12b-bbd114230e25.png)

**Comment by mefengl** [comment]
probably can solve by add `conversationId`
